name = "my-worker"
type = "javascript"

account_id = "4806f2425c6560e67d083f843b83dd5d"
workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2025-03-01"

[build]
command = ""

[[kv_namespaces]]
binding = "HTML_FILES"
id = "4a32186a21504cfbb1334cd938070b8a"
